#!/bin/sh
#PBS -N SRGAN_on_GFS
#PBS -l select=1:ncpus=12:ngpus=3:mpiprocs=1
#PBS -l walltime=500:00:00
#PBS -l place=scatter
#PBS -q gpuq
#PBS -j oe
#PBS -o outscript.out
#PBS -e errscript.err

source /home/SOFTWARE/modulefiles/load_me.sh
module load nvhpc/24.7/cuda/12.5/nvhpc/24.7
source /home/users/bipink/anaconda3/bin/activate VIT_env

cd /home/users/bipink/DIAT/George_Jose/Downscaling/GFS_4x/


python train_gen.py &> test1_output.log
