#!/bin/sh
#PBS -N SRGAN_adv_GFS
#PBS -l select=1:ncpus=16:ngpus=4:mpiprocs=1
#PBS -l walltime=100:00:00
#PBS -l place=scatter
#PBS -q gpuq
#PBS -j oe
#PBS -o outscript.out
#PBS -e errscript.err

source /home/SOFTWARE/modulefiles/load_me.sh
module load nvhpc/24.7/cuda/12.5/nvhpc/24.7
source /home/users/bipink/anaconda3/bin/activate VIT_env

cd /home/users/bipink/DIAT/George_Jose/Downscaling/GFS_4x/


python train_disc.py &> test2_output.log
