#!/bin/sh
#PBS -N VGG_training
#PBS -l select=1:ncpus=4:ngpus=1:mpiprocs=1
#PBS -l walltime=500:00:00
#PBS -l place=scatter
#PBS -q gpuq
#PBS -j oe
#PBS -o outscript.out
#PBS -e errscript.err

source /home/SOFTWARE/modulefiles/load_me.sh
module load nvhpc/24.7/cuda/12.5/nvhpc/24.7
source /home/users/bipink/anaconda3/bin/activate VIT_env

cd /home/users/bipink/DIAT/George_Jose/Downscaling/VGG/


python train.py &> test1_output.log
